export   const dataMovie =[
    {id: Math.random(),
    title: "Godfather", 
    description:"Oscar Movie", 
    posterURL: "https://th-thumbnailer.cdn-si-edu.com/-2YEY5edveISUuO70a_o_ydIvT4=/1072x720/filters:no_upscale():focal(800x602:801x603)/https://tf-cmsv2-smithsonianmag-media.s3.amazonaws.com/filer_public/90/da/90daa208-2dcf-42ed-b2c5-05ce8d306a03/untitled-2.jpg",
    rating: 4},
{id: Math.random(),
    title: "Scent of a Women",
     description:"Oscar Alpaccino", 
     posterURL:"https://m.media-amazon.com/images/I/81RE4096-tL._RI_.jpg", 
     rating: 5},
{id: Math.random(),
    title: "A Beautiful Mind",
     description:"Russel Crowe", 
     posterURL:"https://upload.wikimedia.org/wikipedia/en/b/b8/A_Beautiful_Mind_Poster.jpg", 
     rating: 3},
{id: Math.random(), 
    title: "Troy", 
    description:"Brad Pitt",
     posterURL:"https://resizing.flixster.com/qeP5wc8_Vastxxqnw7twA5Gvul8=/206x305/v2/https://flxt.tmsimg.com/assets/p34313_p_v8_az.jpg", 
     rating: 2},
{id: Math.random(), 
    title: "Sherlock Holmes", 
    description:"Iron Man Actor", 
    posterURL:"https://fr.web.img2.acsta.net/medias/nmedia/18/67/70/22/19227477.jpg", 
    rating: 3} ]